swagger: "2.0"
info:
  description: An invoice scanning service.
  version: "1.0.0"
  title: Invoice API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /invoices:
    post:
      tags:
        - "Invoices"
      summary: "Push a new invoice for processing to the server."
      description: "Push a new invoice for processing"
      consumes:
        - application/json
      parameters:
        - name: invoice
          description: The image of the invoice
          in: body
          required: true
          schema:
            $ref: "#/definitions/InvoiceToScan"
      responses:
        200:
          description: "Successful processing of the invoice"
          schema:
            $ref: "#/definitions/Invoice"
    get:
      tags:
        - "Invoices"
      produces:
        - application/json
      responses:
        200:
          description: The list of invoices
          schema:
            type: array
            items:
              $ref: "#/definitions/Invoice"
  /invoices/{id}:
    get:
      tags:
          - "Invoices"
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: The ID of the invoice to get.
      responses:
          200:
            description: The invoice
            schema:
                $ref: "#/definitions/Invoice"
definitions:
  InvoiceToScan:
    type: object
    required:
      - image
    properties:
      image:
        type: string
        description: The image of the invoice to scan base64 encoded.
      language:
        type: string
      date:
        type: string
  Invoice:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
      text:
        type: string
      image:
        type: string
        description: The image of the invoice base64 encoded.
